// <auto-generated />
using FinalProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(StateContext))]
    [Migration("20231202222305_Direction")]
    partial class Direction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject.Models.Direction", b =>
                {
                    b.Property<string>("DirectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DirectionId");

                    b.ToTable("Directions");

                    b.HasData(
                        new
                        {
                            DirectionId = "No",
                            Name = "North"
                        },
                        new
                        {
                            DirectionId = "Ne",
                            Name = "NorthEast"
                        },
                        new
                        {
                            DirectionId = "Ea",
                            Name = "East"
                        },
                        new
                        {
                            DirectionId = "Se",
                            Name = "SouthEast"
                        },
                        new
                        {
                            DirectionId = "So",
                            Name = "South"
                        },
                        new
                        {
                            DirectionId = "Sw",
                            Name = "SouthWest"
                        },
                        new
                        {
                            DirectionId = "We",
                            Name = "West"
                        },
                        new
                        {
                            DirectionId = "Nw",
                            Name = "NorthWest"
                        });
                });

            modelBuilder.Entity("FinalProject.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateId");

                    b.HasIndex("DirectionId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            Description = "Description",
                            DirectionId = "No",
                            Name = "South Dakota"
                        },
                        new
                        {
                            StateId = 2,
                            Description = "Description",
                            DirectionId = "No",
                            Name = "Minnesota"
                        });
                });

            modelBuilder.Entity("FinalProject.Models.State", b =>
                {
                    b.HasOne("FinalProject.Models.Direction", "Direction")
                        .WithMany()
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direction");
                });
#pragma warning restore 612, 618
        }
    }
}
